bash linting

diff --git a/utils/run_localgrader b/utils/run_localgrader
--- a/utils/run_localgrader
+++ b/utils/run_localgrader
@@ -31,7 +31,7 @@ auto=false
 skip=false
 pdf=false
 
-while getopts ":hifrsp" o; do case "${o}" in
+while getopts ":hifrspa" o; do case "${o}" in
     h) help_message && exit 0 ;;
     i) interactive=true ;;
     f) feedback=true ;;
@@ -57,43 +57,41 @@ PDF_CSS="../../utils/pdf.css"
 SOLUTION_FOLDER="AAASOLUTIONZZZ"
 TEST_ANSWER_FILE="test_answers.txt"
 
-cur=$PWD
-args=("$@")
 declare -a student_files
 
 function get_student_files {
   local student_dir="${1}"
-  mapfile -t -d '' student_files < <(find ${student_dir} -type f \( -name "*.py" -o -name "*.gif" \) -print0)
+  mapfile -t -d '' student_files < <(find "${student_dir}" -type f \( -name "*.py" -o -name "*.gif" \) -print0)
   for file in "${student_files[@]}"; do cp "${file}" .; done
 }
 
 function clean_student_files {
-  for file in "${student_files[@]}"; do rm "$(basename ${file})"; done
+  for file in "${student_files[@]}"; do rm "$(basename "${file}")"; done
 }
 
 function autograde {
   local student_dir="${1}"
   echo -n "autograding ${student_dir}..."
-  python ${AUTOGRADE_SCRIPT} ${student_dir} || error "Error caught: cleaning student files and exiting."
+  python ${AUTOGRADE_SCRIPT} "${student_dir}" || error "Error caught: cleaning student files and exiting."
   grep score "${student_dir}/results.json" | tail -n 1 || echo "No score in results.json. Whatever."
 }
 
 function manualgrade {
   local student_dir="${1}"
-  python ${MANUALGRADE_SCRIPT} ${student_dir} || error "Error caught: cleaning student files and exiting."
+  python ${MANUALGRADE_SCRIPT} "${student_dir}" || error "Error caught: cleaning student files and exiting."
 }
 
 function interactivegrade {
   local student_dir="${1}"
-  autograde $student_dir
-  manualgrade $student_dir
-  read -p "Rerun and reapply autogrades? y/n: " grade_this_dir
+  autograde "$student_dir"
+  manualgrade "$student_dir"
+  read -rp "Rerun and reapply autogrades? y/n: " grade_this_dir
   while [[ ${grade_this_dir} == "y" ]]; do
     clean_student_files
-    get_student_files $student_dir
-    autograde $student_dir
-    manualgrade $student_dir
-    read -p "Rerun and reapply autogrades? y/n: " grade_this_dir
+    get_student_files "$student_dir"
+    autograde "$student_dir"
+    manualgrade "$student_dir"
+    read -rp "Rerun and reapply autogrades? y/n: " grade_this_dir
   done
   echo "On to the next student."
 }
@@ -109,38 +107,39 @@ function generate_pdf {
 function generate_feedback {
   local student_dir="${1}"
   echo "generating feedback for ${student_dir}..."
-  python ${FEEDBACK_SCRIPT} ${student_dir} 0 || error "Error caught: cleaning student files and exiting."
-  local feedback_file=$(find ${student_dir} -type f -name "*.md")
-  mdformat ${feedback_file}
+  python ${FEEDBACK_SCRIPT} "${student_dir}" 0 || error "Error caught: cleaning student files and exiting."
+  local feedback_file
+  feedback_file=$(find "${student_dir}" -type f -name "*.md")
+  mdformat "${feedback_file}"
   if ${pdf}; then
-    generate_pdf ${feedback_file}
+    generate_pdf "${feedback_file}"
   fi
 }
 
 function generate_rubric {
   local student_dir="${1}"
-  autograde $student_dir
-  manualgrade $student_dir
-  python ${FEEDBACK_SCRIPT} ${student_dir} 1 || error "Error caught: cleaning student files and exiting."
+  autograde "$student_dir"
+  manualgrade "$student_dir"
+  python ${FEEDBACK_SCRIPT} "${student_dir}" 1 || error "Error caught: cleaning student files and exiting."
 }
 
 function grade_student_dir {
   local student_dir="${1}"
   if ${interactive}; then
-    get_student_files $student_dir
-    interactivegrade $student_dir
+    get_student_files "$student_dir"
+    interactivegrade "$student_dir"
     clean_student_files
   elif ${auto}; then
-    get_student_files $student_dir
-    autograde $student_dir
+    get_student_files "$student_dir"
+    autograde "$student_dir"
     clean_student_files
   elif ${rubric}; then
-    get_student_files $student_dir
-    generate_rubric $student_dir
+    get_student_files "$student_dir"
+    generate_rubric "$student_dir"
     clean_student_files
   elif ${feedback}; then
-    get_student_files $student_dir
-    generate_feedback $student_dir
+    get_student_files "$student_dir"
+    generate_feedback "$student_dir"
     clean_student_files
   fi
 }
@@ -160,17 +159,17 @@ function ctrl_c() {
 }
 
 if ${rubric}; then
-  student_dir=$(find ${GRADING_DIR} -mindepth 1 -maxdepth 1 -type d -name "*${SOLUTION_FOLDER}*")
+  student_dir=$(find "${GRADING_DIR}" -mindepth 1 -maxdepth 1 -type d -name "*${SOLUTION_FOLDER}*")
   grade_student_dir "${student_dir}/"
 else
-  mapfile -t -d '' dirs < <(find ${GRADING_DIR} -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)
-  mapfile -t -d '' already_graded < <(find ${GRADING_DIR} -type f -name "${TEST_ANSWER_FILE}" -exec dirname {} \; | sort)
+  mapfile -t -d '' dirs < <(find "${GRADING_DIR}" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)
+  mapfile -t -d '' already_graded < <(find "${GRADING_DIR}" -type f -name "${TEST_ANSWER_FILE}" -exec dirname {} \; | sort)
   if ${skip}; then
-    dirs=($(comm --nocheck-order -3 <(printf "%s\n" "${dirs[@]}") <(printf "%s\n" "${already_graded[@]}")))
+    IFS=" " read -r -a dirs <<< "$(comm --nocheck-order -3 <(printf "%s\n" "${dirs[@]}") <(printf "%s\n" "${already_graded[@]}"))"
     echo "Skipping the following directories (already graded):"
     printf '%s\n' "${already_graded[@]}"
   elif ${feedback}; then
-    dirs=(${already_graded[@]})
+    IFS=" " read -r -a dirs <<< "${already_graded[@]}"
     echo "Only considering the following directories (already graded):"
     printf '%s\n' "${dirs[@]}"
   fi
